# Using the official PostgreSQL 15 image as the base
FROM postgres:15

# Set environment variables for the database
# password will be passed at runtime insteading of building it into the image
ENV POSTGRES_USER=admin
ENV POSTGRES_DB=app_db